# Generated by Django 5.1.3 on 2024-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Model',
                'verbose_name_plural': 'Contact Models',
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo/default/')),
                ('big_logo', models.ImageField(upload_to='logo/big/')),
                ('mid_logo', models.ImageField(upload_to='logo/mid/')),
                ('about_description', models.TextField()),
                ('about_2_description', models.TextField()),
                ('about_3_description', models.TextField()),
                ('title_for_about', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('freelancer', models.CharField(max_length=255)),
                ('happy_clients_count', models.PositiveBigIntegerField()),
                ('projects_count', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Main Model',
                'verbose_name_plural': 'Main Models',
            },
        ),
        migrations.CreateModel(
            name='PortfolioImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/')),
            ],
            options={
                'verbose_name': 'Portfolio Image',
                'verbose_name_plural': 'Portfolio Images',
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SocialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('icon', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Social Model',
                'verbose_name_plural': 'Social Models',
            },
        ),
        migrations.CreateModel(
            name='StartsWithIAMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Starts with IAM Model',
                'verbose_name_plural': 'Starts with IAM Models',
            },
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(to='common.portfolioimagesmodel')),
            ],
        ),
    ]
