# Generated by Django 5.1.3 on 2024-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_mainmodel_born_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='name_for_full',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
