# Generated by Django 5.1.3 on 2024-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_portfoliomodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
